### ISSUE TITLE
Tutorial page

### ISSUE THREAD

**Issue by gerroon** [wiebow/scramblernd.game2d#1]
Hi

I followed the tutorials first page as it porgressed. I was able to get the code compile but I cant run it. 

Was the code order supposed to be same as how it progressed on the tutorial page 1?

Btw I just realized that this was supposed to be for the C64 tetris game, sorry that I posted it under the wrong game. I misclicked it.

thanks

**Comment by wiebow** [comment]
hi @gerroon No problem.       The blog posts are not really meant as LITERAL tutorials.  The code you see in the posts is not always what it is should be, because I also fixed bugs that are NOT in later posts.  The series was meant to show what it takes to code a game in ASM from scratch.   So if you want to look at the correct code, go to the repository.

Thanks for your comment, I hope you like series and have fun with it.
